### PR TITLE
feat: add `rem` transform

### PR DESCRIPTION
**Pull request by schardev**

### CODE REVIEW

**Comment by jorenbroekema** [comment]
Very soon when style-dictionary v4 is released as well as this package v1, we will not need this anymore as you can just use the style-dictionary built-in rem transform: https://v4.styledictionary.com/reference/hooks/transforms/predefined/#sizerem

You would use it like this:

```json
{
  "source": ["tokens/**/*.json"],
  "preprocessors": ["tokens-studio"],
  "platforms": {
    "css": {
      "transformGroup": "tokens-studio",
      "transforms": ["size/rem", "name/kebab"],
      "basePxFontSize": 14,
      "buildPath": "build/css/",
      "files": [
        {
          "destination": "variables.css",
          "format": "css/variables"
        }
      ]
    }
  }
}
```

The "tokens-studio" preprocessor will ensure that spacing/sizing/borderRadius types are aligned to DTCG "dimension" type, and the built-in transform in style-dictionary will do the rest (it matches "dimension" and "fontSize" type tokens).

You can pass `basePxFontSize` property on the platform config level which by default will be 16, but you can pick any number.

**Comment by schardev** [comment]
That's great. I just wish the documention to be a bit clear. It's confusing because of the mismatch between token-studio and Style Dictionary. Hopefully not for long :)

Thanks.

**Comment by FSou1** [comment]
> ```json
> "basePxFontSize": 14,
> ```

Hey @jorenbroekema, does it work for you?

**Comment by jorenbroekema** [comment]
Yup should work

**Pull request closed without merging**
